# this data isn't in FishData; download manually from OceanAdapt and wrangle into the same format

# 1. Download data: go to https://oceanadapt.rutgers.edu/ -> download data -> fill out box with your personal info -> scroll down and click "download raw data" (we did this Oct 2 2019)
# 2. Store data: open the .zip file and move the folder it contains to the raw-data folder of the project directory (range-edges/raw-data). Go through the readme and other informative documentation. There are lots of useful occurrence datasets here; we'll use dat_exploded because it is zero-inflated, which is required for VAST. 
# 3. Regenerate data, VERY IMPORTANT: The datasets in the OceanAdapt download are generated by compile.R, which uses some defaults that are not appropriate for VAST. In particular, it drops data-poor years, but we can still use those in VAST. To re-generate the dataset needed, open compile.R, change HQ_DATA_ONLY <- FALSE and DAT_EXPLODED <- TRUE and run the entire script, regenerating dat_exploded.Rdata

library(here)
library(tidyverse)

load(here("raw-data/mpinsky-OceanAdapt-9815545/data_clean","dat_exploded.RData")) # may have to revise this path if future downloads of OceanAdapt are renamed 

oceanadapt_raw <- dat.exploded %>%
  filter(region=="Northeast US Spring")

# try to make consistent with Catch_rates dfs generated for other regions by FishData::download_catch_rates (try generating one for EBS and compare)
# needs to be zero-inflated data so we have records of every time a species was absent! 
neus_catch_rates <- oceanadapt_raw %>%
  rename(Sci = spp,
         Year = year,
         Lat = lat,
         Long = lon,
         Wt = wtcpue,
         TowID = haulid,
         Depth_m = depth) %>%
  select(-stratum, -stratumarea, -common, -region) %>%
  filter(!is.na(Sci))  

write_rds(neus_catch_rates, here("processed-data","neus_catch_rates.rds"))
rm(list=ls())